FROM harbor.hiotc.pro/saas-test/node:13.3.0-stretch
#FROM node:13.3.0-stretch

WORKDIR /data/chainup/node/exchange-vue-server-otc

ADD ./ /data/chainup/node/exchange-vue-server-otc

EXPOSE 7002

ENTRYPOINT npm run start-exchange-vue-server-otc
