<template>
  <div id="app" :class="pageTheme" class="b-2-cl" style="position: relative; min-height: 800px">
    <c-tip />
    <!-- 改，2022.12.05，多图不展示头部 -->
    <c-header :class="headClass" v-if="!hideheade && calTradeType != 'showMore'" />
    <!-- 改，2022.10.01，新增style -->
    <!-- 改，2022.12.05，新增 calPageContent 样式控制 -->
    <div
      class="page-content"
      :class="{ 'page-content-chain': hideheade || navigationType === '1' }"
      style="position: relative; min-height: 800px; padding-top: 60px"
      :style="calPageContent"
    >
      <transition
        enter-active-class="animated fadeIn"
        leave-active-class="animated fadeOut"
        mode="out-in"
        duration="200"
      >
        <router-view />
      </transition>
    </div>
    <!-- 改，2022.12.05，多图不展示底部 -->
    <c-footer :class="footerClass" v-if="!hideFooter && calTradeType != 'showMore'" />
    <div v-if="showMask" class="m-mask" @click.stop="()=>{}"></div>
  </div>
</template>

<script>
import commonMixin from "@/components/BlockChain-ui-privatization/PC/pages/pages";
import mixin from "@/components/BlockChain-ui-privatization/PC/pages/ex-home/ex-home";
import "@/components/BlockChain-ui-privatization/PC/pages/ex-home/ex-home.styl";
import { mapGetters } from "vuex";

export default {
  mixins: [commonMixin, mixin],
  data() {
    return {
      showMask: true,
    };
  },
  mounted() {
    this.init();
    this.getPublicInfo();
    // setTimeout(() => {
    //   this.embedded_script();
    // }, 2000);
    this.$bus.$on("limit_ip", (val) => {
      this.showMask = val;
    });
  },
  // 改，2022.12.05 新增是否展示多图计算属性
  computed: {
    ...mapGetters(["calTradeType"]),
    calPageContent() {
      if (this.calTradeType == 'showMore') {
        return {
          paddingTop: '0px',
          height: '550px',
          minHeight: 'unset',
        };
      }
      return {};
    },
  },
  methods: {
    // 获取公共数据
    getPublicInfo() {
      const data = {
        market: {
          USDT: {
            "POL/USDT": {
              limitVolumeMin: 0.1,
              symbol: "polusdt",
              showName: "POL/USDT",
              marketBuyMin: 0.0001,
              is_grid_open: 0,
              multiple: 3,
              isOnlyHoldShow: 0,
              IsST: 0,
              marketSellMin: 0.1,
              sort: 1,
              etfOpen: 0,
              quoteFeeRate: "0",
              newcoinFlag: 0,
              isShow: 1,
              volume: 1,
              depth: "0.0001,0.001,0.01",
              tradingStartTime: 1760582222000,
              price: 4,
              IsMine: "0",
              name: "POL/USDT",
              limitPriceMin: 0.0001,
              IsLimitPlat: "0",
              is_open_lever: 1,
              openQuoteFee: 0,
            },
            "BTC/USDT": {
              limitVolumeMin: 0.001,
              symbol: "btcusdt",
              showName: "BTC/USDT",
              marketBuyMin: 100,
              is_grid_open: 0,
              multiple: 3,
              isOnlyHoldShow: 0,
              IsST: 0,
              marketSellMin: 0.001,
              sort: 2,
              etfOpen: 0,
              quoteFeeRate: 0.001,
              newcoinFlag: 0,
              isShow: 1,
              volume: 5,
              depth: "0.01,0.1,1",
              tradingStartTime: 1752829517000,
              price: 2,
              IsMine: "0",
              name: "BTC/USDT",
              limitPriceMin: 5000,
              IsLimitPlat: "0",
              is_open_lever: 1,
              openQuoteFee: 0,
            },
            "ETH/USDT": {
              limitVolumeMin: 0.001,
              symbol: "ethusdt",
              showName: "ETH/USDT",
              marketBuyMin: 500,
              is_grid_open: 0,
              multiple: 3,
              isOnlyHoldShow: 0,
              IsST: 0,
              marketSellMin: 0.001,
              sort: 3,
              etfOpen: 0,
              quoteFeeRate: 0.001,
              newcoinFlag: 0,
              isShow: 1,
              volume: 4,
              depth: "0.01,0.1,1",
              tradingStartTime: 1752829499000,
              price: 2,
              IsMine: "0",
              name: "ETH/USDT",
              limitPriceMin: 500,
              IsLimitPlat: "0",
              is_open_lever: 1,
              openQuoteFee: 0,
            },
            "TRX/USDT": {
              limitVolumeMin: 0.1,
              symbol: "trxusdt",
              showName: "TRX/USDT",
              marketBuyMin: 0.0001,
              is_grid_open: 0,
              multiple: 3,
              isOnlyHoldShow: 0,
              IsST: 0,
              marketSellMin: 0.1,
              sort: 4,
              etfOpen: 0,
              quoteFeeRate: "0",
              newcoinFlag: 0,
              isShow: 1,
              volume: 1,
              depth: "0.0001,0.001,0.01",
              tradingStartTime: 1752819663000,
              price: 4,
              IsMine: "0",
              name: "TRX/USDT",
              limitPriceMin: 0.0001,
              IsLimitPlat: "0",
              is_open_lever: 1,
              openQuoteFee: 0,
            },
            "BNB/USDT": {
              limitVolumeMin: 0.0001,
              symbol: "bnbusdt",
              showName: "BNB/USDT",
              marketBuyMin: 0.01,
              is_grid_open: 0,
              multiple: 3,
              isOnlyHoldShow: 0,
              IsST: 0,
              marketSellMin: 0.0001,
              sort: 5,
              etfOpen: 0,
              quoteFeeRate: "0",
              newcoinFlag: 0,
              isShow: 1,
              volume: 3,
              depth: "0.01,0.1,1",
              tradingStartTime: 1752829323000,
              price: 2,
              IsMine: "0",
              name: "BNB/USDT",
              limitPriceMin: 0.01,
              IsLimitPlat: "0",
              is_open_lever: 1,
              openQuoteFee: 0,
            },
            "SOL/USDT": {
              limitVolumeMin: 0.001,
              symbol: "solusdt",
              showName: "SOL/USDT",
              marketBuyMin: 0.01,
              is_grid_open: 0,
              multiple: 3,
              isOnlyHoldShow: 0,
              IsST: 0,
              marketSellMin: 0.001,
              sort: 6,
              etfOpen: 0,
              quoteFeeRate: "0",
              newcoinFlag: 0,
              isShow: 1,
              volume: 3,
              depth: "0.01,0.1,1",
              tradingStartTime: 1752829461000,
              price: 2,
              IsMine: "0",
              name: "SOL/USDT",
              limitPriceMin: 0.01,
              IsLimitPlat: "0",
              is_open_lever: 1,
              openQuoteFee: 0,
            },
            "USDC/USDT": {
              limitVolumeMin: 1,
              symbol: "usdcusdt",
              showName: "USDC/USDT",
              marketBuyMin: 0.0001,
              is_grid_open: 0,
              multiple: 3,
              isOnlyHoldShow: 0,
              IsST: 0,
              marketSellMin: 1,
              sort: 7,
              etfOpen: 0,
              quoteFeeRate: "0",
              newcoinFlag: 0,
              isShow: 1,
              volume: 0,
              depth: "0.0001,0.001,0.01",
              tradingStartTime: 1760521770000,
              price: 4,
              IsMine: "0",
              name: "USDC/USDT",
              limitPriceMin: 0.0001,
              IsLimitPlat: "0",
              is_open_lever: 0,
              openQuoteFee: 0,
            },
          },
        },
        wsUrl: "wss://ws.sparkbit.io/kline-api/ws",
        followCoinList: {
          USDT: {
            USDT: {
              showName: "USDT",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "BNB Smart Chain",
              icon: "https://oss.sparkbit.io/images/logo/usdt_logo.webp",
              sort: 0,
              tokenBase: "ETH",
              mainChainSymbol: "USDT",
              isOvercharge: 0,
              otcOpen: 1,
              name: "USDT",
              tagType: 0,
              mainChainType: 1,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            AVAXCUSDT: {
              showName: "AVAXCUSDT",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "AVAX C-Chain",
              icon: "",
              sort: 1,
              tokenBase: "ETH",
              mainChainSymbol: "USDT",
              isOvercharge: 0,
              otcOpen: 0,
              name: "AVAXCUSDT",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            PUSDT: {
              showName: "PUSDT",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "Polygon",
              icon: "",
              sort: 1,
              tokenBase: "ETH",
              mainChainSymbol: "USDT",
              isOvercharge: 0,
              otcOpen: 0,
              name: "PUSDT",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            EUSDT: {
              showName: "EUSDT",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "ERC 20",
              icon: "",
              sort: 6,
              tokenBase: "ETH",
              mainChainSymbol: "USDT",
              isOvercharge: 0,
              otcOpen: 0,
              name: "EUSDT",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            TUSDT: {
              showName: "TUSDT",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "TRC 20",
              icon: "",
              sort: 7,
              tokenBase: "TRX",
              mainChainSymbol: "USDT",
              isOvercharge: 0,
              otcOpen: 0,
              name: "TUSDT",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            SUSDT: {
              showName: "SUSDT",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "Solana",
              icon: "",
              sort: 8,
              tokenBase: "SUSDT",
              mainChainSymbol: "USDT",
              isOvercharge: 0,
              otcOpen: 0,
              name: "SUSDT",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
          },
          BTC: {
            BTC: {
              showName: "BTC",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "2",
              mainChainName: "BNB Smart Chain",
              icon: "https://oss.sparkbit.io/images/logo/btc_logo.webp",
              sort: 1,
              tokenBase: "BNB",
              mainChainSymbol: "BTC",
              isOvercharge: 0,
              otcOpen: 0,
              name: "BTC",
              tagType: 0,
              mainChainType: 1,
              showPrecision: 5,
              isOverchargeMsg: {},
            },
            EWBTC: {
              showName: "EWBTC",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "ERC 20",
              icon: "",
              sort: 1,
              tokenBase: "ETH",
              mainChainSymbol: "BTC",
              isOvercharge: 0,
              otcOpen: 0,
              name: "EWBTC",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            WBTC: {
              showName: "WBTC",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "Polygon",
              icon: "",
              sort: 1,
              tokenBase: "ETH",
              mainChainSymbol: "BTC",
              isOvercharge: 0,
              otcOpen: 0,
              name: "WBTC",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            AVAXBTC: {
              showName: "AVAXBTC",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "AVAX C-Chain",
              icon: "",
              sort: 1,
              tokenBase: "ETH",
              mainChainSymbol: "BTC",
              isOvercharge: 0,
              otcOpen: 0,
              name: "AVAXBTC",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
          },
          MORPHO: {},
          POL: {
            POL: {
              showName: "POL",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "Polygon",
              icon: "https://oss.sparkbit.io/images/logo/pol_logo.webp",
              sort: 1,
              tokenBase: "POL",
              mainChainSymbol: "POL",
              isOvercharge: 0,
              otcOpen: 0,
              name: "POL",
              tagType: 0,
              mainChainType: 1,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            EPOL: {
              showName: "EPOL",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "Ethereum",
              icon: "",
              sort: 1,
              tokenBase: "ETH",
              mainChainSymbol: "POL",
              isOvercharge: 0,
              otcOpen: 0,
              name: "EPOL",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
          },
          ETH: {
            AVAXWETH: {
              showName: "AVAXWETH",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "AVAX C-Chain",
              icon: "",
              sort: 1,
              tokenBase: "ETH",
              mainChainSymbol: "ETH",
              isOvercharge: 0,
              otcOpen: 0,
              name: "AVAXWETH",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            TETH: {
              showName: "TETH",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "TRC 20",
              icon: "",
              sort: 1,
              tokenBase: "TRX",
              mainChainSymbol: "ETH",
              isOvercharge: 0,
              otcOpen: 0,
              name: "TETH",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            PWETH: {
              showName: "PWETH",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "Polygon",
              icon: "",
              sort: 1,
              tokenBase: "ETH",
              mainChainSymbol: "ETH",
              isOvercharge: 0,
              otcOpen: 0,
              name: "PWETH",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            SWETH: {
              showName: "SWETH",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "Solana",
              icon: "",
              sort: 1,
              tokenBase: "SWETH",
              mainChainSymbol: "ETH",
              isOvercharge: 0,
              otcOpen: 0,
              name: "SWETH",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            BETH: {
              showName: "BETH",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "BNB Smart Chain",
              icon: "",
              sort: 1,
              tokenBase: "ETH",
              mainChainSymbol: "ETH",
              isOvercharge: 0,
              otcOpen: 0,
              name: "BETH",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            ETH: {
              showName: "ETH",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "ERC 20",
              icon: "https://oss.sparkbit.io/images/logo/eth_logo.webp",
              sort: 2,
              tokenBase: "ETH",
              mainChainSymbol: "ETH",
              isOvercharge: 0,
              otcOpen: 0,
              name: "ETH",
              tagType: 0,
              mainChainType: 1,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
          },
          TRX: {
            BTRX: {
              showName: "BTRX",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "BNB Smart Chain",
              icon: "",
              sort: 1,
              tokenBase: "ETH",
              mainChainSymbol: "TRX",
              isOvercharge: 0,
              otcOpen: 0,
              name: "BTRX",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            ETRX: {
              showName: "ETRX",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "ERC 20",
              icon: "",
              sort: 1,
              tokenBase: "ETH",
              mainChainSymbol: "TRX",
              isOvercharge: 0,
              otcOpen: 0,
              name: "ETRX",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            STRX: {
              showName: "STRX",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "Solana",
              icon: "",
              sort: 1,
              tokenBase: "STRX",
              mainChainSymbol: "TRX",
              isOvercharge: 0,
              otcOpen: 0,
              name: "STRX",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            TRX: {
              showName: "TRX",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "TRX 20",
              icon: "https://oss.sparkbit.io/images/logo/trx_logo.webp",
              sort: 3,
              tokenBase: "TRX",
              mainChainSymbol: "TRX",
              isOvercharge: 0,
              otcOpen: 0,
              name: "TRX",
              tagType: 0,
              mainChainType: 1,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
          },
          SOL: {
            PSOL: {
              showName: "PSOL",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "Polygon",
              icon: "",
              sort: 1,
              tokenBase: "ETH",
              mainChainSymbol: "SOL",
              isOvercharge: 0,
              otcOpen: 0,
              name: "PSOL",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            ESOL: {
              showName: "ESOL",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "ERC 20",
              icon: "",
              sort: 1,
              tokenBase: "ETH",
              mainChainSymbol: "SOL",
              isOvercharge: 0,
              otcOpen: 0,
              name: "ESOL",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            TSOL: {
              showName: "TSOL",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "TRC 20",
              icon: "",
              sort: 1,
              tokenBase: "TRX",
              mainChainSymbol: "SOL",
              isOvercharge: 0,
              otcOpen: 0,
              name: "TSOL",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            BSOL: {
              showName: "BSOL",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "BNB Smart Chain",
              icon: "",
              sort: 1,
              tokenBase: "ETH",
              mainChainSymbol: "SOL",
              isOvercharge: 0,
              otcOpen: 0,
              name: "BSOL",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            SOL: {
              showName: "SOL",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "Solana",
              icon: "https://oss.sparkbit.io/images/logo/sol_logo.webp",
              sort: 4,
              tokenBase: "SOL",
              mainChainSymbol: "SOL",
              isOvercharge: 0,
              otcOpen: 0,
              name: "SOL",
              tagType: 0,
              mainChainType: 1,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
          },
          BNB: {
            PBNB: {
              showName: "PBNB",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "Polygon",
              icon: "",
              sort: 1,
              tokenBase: "ETH",
              mainChainSymbol: "BNB",
              isOvercharge: 0,
              otcOpen: 0,
              name: "PBNB",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            EBNB: {
              showName: "EBNB",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "ERC 20",
              icon: "",
              sort: 1,
              tokenBase: "ETH",
              mainChainSymbol: "BNB",
              isOvercharge: 0,
              otcOpen: 0,
              name: "EBNB",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            SBNB: {
              showName: "SBNB",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "SBNB",
              icon: "",
              sort: 1,
              tokenBase: "SBNB",
              mainChainSymbol: "BNB",
              isOvercharge: 0,
              otcOpen: 0,
              name: "SBNB",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            BNB: {
              showName: "BNB",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "BNB Smart Chain",
              icon: "https://oss.sparkbit.io/images/logo/bnb_logo.webp",
              sort: 9,
              tokenBase: "BNB",
              mainChainSymbol: "BNB",
              isOvercharge: 0,
              otcOpen: 0,
              name: "BNB",
              tagType: 0,
              mainChainType: 1,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
          },
          USDC: {
            BUSDC: {
              showName: "BUSDC",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "BNB Smart Chain",
              icon: "",
              sort: 1,
              tokenBase: "ETH",
              mainChainSymbol: "USDC",
              isOvercharge: 0,
              otcOpen: 0,
              name: "BUSDC",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            AVAXUSDC: {
              showName: "AVAXUSDC",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "AVAX C-Chain",
              icon: "",
              sort: 1,
              tokenBase: "ETH",
              mainChainSymbol: "USDC",
              isOvercharge: 0,
              otcOpen: 0,
              name: "AVAXUSDC",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            TUSDC: {
              showName: "TUSDC",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "TRC 20",
              icon: "",
              sort: 1,
              tokenBase: "TRX",
              mainChainSymbol: "USDC",
              isOvercharge: 0,
              otcOpen: 0,
              name: "TUSDC",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            SUSDC: {
              showName: "SUSDC",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "Solana",
              icon: "",
              sort: 1,
              tokenBase: "SUSDC",
              mainChainSymbol: "USDC",
              isOvercharge: 0,
              otcOpen: 0,
              name: "SUSDC",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            PUSDC: {
              showName: "PUSDC",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "Polygon",
              icon: "",
              sort: 1,
              tokenBase: "ETH",
              mainChainSymbol: "USDC",
              isOvercharge: 0,
              otcOpen: 0,
              name: "PUSDC",
              tagType: 0,
              mainChainType: 2,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
            USDC: {
              showName: "USDC",
              fiatPrecision: {
                krw: "2",
                jpy: 2,
                usd: "2",
                cny: "2",
              },
              coinTag: "",
              mainChainName: "ERC 20",
              icon: "https://oss.sparkbit.io/images/logo/usdc_logo.webp",
              sort: 111,
              tokenBase: "ETH",
              mainChainSymbol: "USDC",
              isOvercharge: 0,
              otcOpen: 0,
              name: "USDC",
              tagType: 0,
              mainChainType: 1,
              showPrecision: 2,
              isOverchargeMsg: {},
            },
          },
        },
        rate: {
          ko_KR: {
            coin_precision: "2",
            MORPHO: 2534.7729311268,
            symbolPrecision: "0",
            lang_coin: "KRW",
            USDT: 1425.01666733,
            POL: 265.623106790312,
            BTC: 155804168.8221922,
            SOL: 263499.8319559903,
            KRW: "1",
            lang_logo: "₩",
            CFX: 16.12575325155197,
            BNB: 1566777.3253959883,
            ETH: 5448750.72986968,
            USDC: 1425.301670663466,
            TRX: 420.237415195617,
          },
          en_US: {
            coin_precision: "2",
            MORPHO: 1.8207098,
            symbolPrecision: "2",
            USD: "1",
            lang_coin: "USD",
            USDT: 0.9994,
            POL: 0.18628816,
            BTC: 109384.689506,
            SOL: 184.799054,
            lang_logo: "$",
            CFX: 0.011580587232745,
            BNB: 1098.820312,
            ETH: 3825.372908,
            USDC: 0.99959988,
            TRX: 0.29472306,
          },
          zh_CN: {
            coin_precision: "2",
            MORPHO: 12.9682278362,
            symbolPrecision: "2",
            USD: 7.11510822,
            lang_coin: "CNY",
            USDT: 7.11510822,
            POL: 1.326256172208,
            CNY: "1",
            BTC: 777930.21493153,
            SOL: 1315.6546609602,
            lang_logo: "￥",
            CFX: 0.082501449983334,
            BNB: 7822.9191857256,
            ETH: 27205.61239432,
            USDC: 7.116531241644,
            TRX: 2.098245414078,
            EC: 1,
          },
          ja_JP: {
            coin_precision: 2,
            MORPHO: 268.7405935396,
            symbolPrecision: 2,
            lang_coin: "JPY",
            USDT: 154.26053351,
            POL: 28.754163446264,
            BTC: 16866072.34610517,
            SOL: 28524.3152513341,
            JPY: "1",
            lang_logo: "¥",
            CFX: 1.709965831141451,
            BNB: 169606.3713835748,
            ETH: 589836.74635017,
            USDC: 154.291385616702,
            TRX: 45.491431332099,
          },
        },
        headerSymbol: ["BTC/USDT", "ETH/USDT", "BNB/USDT"],
        maket_index: "BTC",
        coinList: {
          USDT: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "USDT",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "BNB Smart Chain",
            icon: "https://oss.sparkbit.io/images/logo/usdt_logo.webp",
            sort: 0,
            tokenBase: "ETH",
            mainChainSymbol: "USDT",
            isOvercharge: 0,
            otcOpen: 1,
            name: "USDT",
            tagType: 0,
            mainChainType: 1,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          AVAXWETH: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "AVAXWETH",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "AVAX C-Chain",
            icon: "",
            sort: 1,
            tokenBase: "ETH",
            mainChainSymbol: "ETH",
            isOvercharge: 0,
            otcOpen: 0,
            name: "AVAXWETH",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          TETH: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "TETH",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "TRC 20",
            icon: "",
            sort: 1,
            tokenBase: "TRX",
            mainChainSymbol: "ETH",
            isOvercharge: 0,
            otcOpen: 0,
            name: "TETH",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          PBNB: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "PBNB",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "Polygon",
            icon: "",
            sort: 1,
            tokenBase: "ETH",
            mainChainSymbol: "BNB",
            isOvercharge: 0,
            otcOpen: 0,
            name: "PBNB",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          PSOL: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "PSOL",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "Polygon",
            icon: "",
            sort: 1,
            tokenBase: "ETH",
            mainChainSymbol: "SOL",
            isOvercharge: 0,
            otcOpen: 0,
            name: "PSOL",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          BTRX: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "BTRX",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "BNB Smart Chain",
            icon: "",
            sort: 1,
            tokenBase: "ETH",
            mainChainSymbol: "TRX",
            isOvercharge: 0,
            otcOpen: 0,
            name: "BTRX",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          ETRX: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "ETRX",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "ERC 20",
            icon: "",
            sort: 1,
            tokenBase: "ETH",
            mainChainSymbol: "TRX",
            isOvercharge: 0,
            otcOpen: 0,
            name: "ETRX",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          BUSDC: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "BUSDC",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "BNB Smart Chain",
            icon: "",
            sort: 1,
            tokenBase: "ETH",
            mainChainSymbol: "USDC",
            isOvercharge: 0,
            otcOpen: 0,
            name: "BUSDC",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          PWETH: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "PWETH",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "Polygon",
            icon: "",
            sort: 1,
            tokenBase: "ETH",
            mainChainSymbol: "ETH",
            isOvercharge: 0,
            otcOpen: 0,
            name: "PWETH",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          AVAXUSDC: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "AVAXUSDC",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "AVAX C-Chain",
            icon: "",
            sort: 1,
            tokenBase: "ETH",
            mainChainSymbol: "USDC",
            isOvercharge: 0,
            otcOpen: 0,
            name: "AVAXUSDC",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          ESOL: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "ESOL",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "ERC 20",
            icon: "",
            sort: 1,
            tokenBase: "ETH",
            mainChainSymbol: "SOL",
            isOvercharge: 0,
            otcOpen: 0,
            name: "ESOL",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          POL: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "POL",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "Polygon",
            icon: "https://oss.sparkbit.io/images/logo/pol_logo.webp",
            sort: 1,
            tokenBase: "POL",
            mainChainSymbol: "POL",
            isOvercharge: 0,
            otcOpen: 0,
            name: "POL",
            tagType: 0,
            mainChainType: 1,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          SWETH: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "SWETH",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "Solana",
            icon: "",
            sort: 1,
            tokenBase: "SWETH",
            mainChainSymbol: "ETH",
            isOvercharge: 0,
            otcOpen: 0,
            name: "SWETH",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          BTC: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "BTC",
            coinTag: "2",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "BNB Smart Chain",
            icon: "https://oss.sparkbit.io/images/logo/btc_logo.webp",
            sort: 1,
            tokenBase: "BNB",
            mainChainSymbol: "BTC",
            isOvercharge: 0,
            otcOpen: 0,
            name: "BTC",
            tagType: 0,
            mainChainType: 1,
            showPrecision: 5,
            isOverchargeMsg: {},
          },
          EBNB: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "EBNB",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "ERC 20",
            icon: "",
            sort: 1,
            tokenBase: "ETH",
            mainChainSymbol: "BNB",
            isOvercharge: 0,
            otcOpen: 0,
            name: "EBNB",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          TUSDC: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "TUSDC",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "TRC 20",
            icon: "",
            sort: 1,
            tokenBase: "TRX",
            mainChainSymbol: "USDC",
            isOvercharge: 0,
            otcOpen: 0,
            name: "TUSDC",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          AVAXCUSDT: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "AVAXCUSDT",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "AVAX C-Chain",
            icon: "",
            sort: 1,
            tokenBase: "ETH",
            mainChainSymbol: "USDT",
            isOvercharge: 0,
            otcOpen: 0,
            name: "AVAXCUSDT",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          TSOL: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "TSOL",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "TRC 20",
            icon: "",
            sort: 1,
            tokenBase: "TRX",
            mainChainSymbol: "SOL",
            isOvercharge: 0,
            otcOpen: 0,
            name: "TSOL",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          STRX: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "STRX",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "Solana",
            icon: "",
            sort: 1,
            tokenBase: "STRX",
            mainChainSymbol: "TRX",
            isOvercharge: 0,
            otcOpen: 0,
            name: "STRX",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          SUSDC: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "SUSDC",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "Solana",
            icon: "",
            sort: 1,
            tokenBase: "SUSDC",
            mainChainSymbol: "USDC",
            isOvercharge: 0,
            otcOpen: 0,
            name: "SUSDC",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          EWBTC: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "EWBTC",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "ERC 20",
            icon: "",
            sort: 1,
            tokenBase: "ETH",
            mainChainSymbol: "BTC",
            isOvercharge: 0,
            otcOpen: 0,
            name: "EWBTC",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          WBTC: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "WBTC",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "Polygon",
            icon: "",
            sort: 1,
            tokenBase: "ETH",
            mainChainSymbol: "BTC",
            isOvercharge: 0,
            otcOpen: 0,
            name: "WBTC",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          PUSDC: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "PUSDC",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "Polygon",
            icon: "",
            sort: 1,
            tokenBase: "ETH",
            mainChainSymbol: "USDC",
            isOvercharge: 0,
            otcOpen: 0,
            name: "PUSDC",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          SBNB: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "SBNB",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "SBNB",
            icon: "",
            sort: 1,
            tokenBase: "SBNB",
            mainChainSymbol: "BNB",
            isOvercharge: 0,
            otcOpen: 0,
            name: "SBNB",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          BETH: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "BETH",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "BNB Smart Chain",
            icon: "",
            sort: 1,
            tokenBase: "ETH",
            mainChainSymbol: "ETH",
            isOvercharge: 0,
            otcOpen: 0,
            name: "BETH",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          EPOL: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "EPOL",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "Ethereum",
            icon: "",
            sort: 1,
            tokenBase: "ETH",
            mainChainSymbol: "POL",
            isOvercharge: 0,
            otcOpen: 0,
            name: "EPOL",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          PUSDT: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "PUSDT",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "Polygon",
            icon: "",
            sort: 1,
            tokenBase: "ETH",
            mainChainSymbol: "USDT",
            isOvercharge: 0,
            otcOpen: 0,
            name: "PUSDT",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          BSOL: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "BSOL",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "BNB Smart Chain",
            icon: "",
            sort: 1,
            tokenBase: "ETH",
            mainChainSymbol: "SOL",
            isOvercharge: 0,
            otcOpen: 0,
            name: "BSOL",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          AVAXBTC: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "AVAXBTC",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "AVAX C-Chain",
            icon: "",
            sort: 1,
            tokenBase: "ETH",
            mainChainSymbol: "BTC",
            isOvercharge: 0,
            otcOpen: 0,
            name: "AVAXBTC",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          ETH: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "ETH",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "ERC 20",
            icon: "https://oss.sparkbit.io/images/logo/eth_logo.webp",
            sort: 2,
            tokenBase: "ETH",
            mainChainSymbol: "ETH",
            isOvercharge: 0,
            otcOpen: 0,
            name: "ETH",
            tagType: 0,
            mainChainType: 1,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          TRX: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "TRX",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "TRX 20",
            icon: "https://oss.sparkbit.io/images/logo/trx_logo.webp",
            sort: 3,
            tokenBase: "TRX",
            mainChainSymbol: "TRX",
            isOvercharge: 0,
            otcOpen: 0,
            name: "TRX",
            tagType: 0,
            mainChainType: 1,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          SOL: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "SOL",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "Solana",
            icon: "https://oss.sparkbit.io/images/logo/sol_logo.webp",
            sort: 4,
            tokenBase: "SOL",
            mainChainSymbol: "SOL",
            isOvercharge: 0,
            otcOpen: 0,
            name: "SOL",
            tagType: 0,
            mainChainType: 1,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          EUSDT: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "EUSDT",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "ERC 20",
            icon: "",
            sort: 6,
            tokenBase: "ETH",
            mainChainSymbol: "USDT",
            isOvercharge: 0,
            otcOpen: 0,
            name: "EUSDT",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          TUSDT: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "TUSDT",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "TRC 20",
            icon: "",
            sort: 7,
            tokenBase: "TRX",
            mainChainSymbol: "USDT",
            isOvercharge: 0,
            otcOpen: 0,
            name: "TUSDT",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          SUSDT: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "SUSDT",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "Solana",
            icon: "",
            sort: 8,
            tokenBase: "SUSDT",
            mainChainSymbol: "USDT",
            isOvercharge: 0,
            otcOpen: 0,
            name: "SUSDT",
            tagType: 0,
            mainChainType: 2,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          BNB: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "BNB",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "BNB Smart Chain",
            icon: "https://oss.sparkbit.io/images/logo/bnb_logo.webp",
            sort: 9,
            tokenBase: "BNB",
            mainChainSymbol: "BNB",
            isOvercharge: 0,
            otcOpen: 0,
            name: "BNB",
            tagType: 0,
            mainChainType: 1,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
          USDC: {
            isFiat: 0,
            fiatPrecision: {
              krw: "2",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            showName: "USDC",
            coinTag: "",
            symbolPrecision: {
              krw: "0",
              jpy: 2,
              usd: "2",
              cny: "2",
            },
            mainChainName: "ERC 20",
            icon: "https://oss.sparkbit.io/images/logo/usdc_logo.webp",
            sort: 111,
            tokenBase: "ETH",
            mainChainSymbol: "USDC",
            isOvercharge: 0,
            otcOpen: 0,
            name: "USDC",
            tagType: 0,
            mainChainType: 1,
            showPrecision: 2,
            isOverchargeMsg: {},
          },
        },
        klineScale: ["1min", "5min", "15min", "30min", "60min", "4h", "1day", "1week", "1month"],
        marketSort: ["USDT"],
        coinTagLangs: {
          ru_RU: {
            1: "Половина",
            2: "New",
            3: "Популярные",
            4: "ETF",
          },
          el_GR: {
            1: "減半",
            2: "上新",
            3: "熱門",
            4: "ETF",
          },
          ko_KR: {
            1: "할빼기",
            2: "New",
            3: "인기",
            4: "ETF",
          },
          en_US: {
            1: "Halve",
            2: "New",
            3: "Hot",
            4: "ETF",
          },
          zh_CN: {
            1: "减半",
            2: "上新",
            3: "热门",
            4: "ETF",
          },
          vi_VN: {
            1: "Giảm một nửa",
            2: "New",
            3: "Hot",
            4: "ETF",
          },
          mn_MN: {
            2: "New",
            4: "ETF",
          },
          ja_JP: {
            1: "ハービング",
            2: "New",
            3: "人気",
            4: "ETF",
          },
        },
      };
      this.$bus.$emit("PublicInfoV4", data);
      // this.axios({
      //   url: this.$store.state.url.common.public_info,
      // })
      //   .then((res) => {
      //     const data = res.data.market;
      //     this.$bus.$emit("PublicInfoV4", data);
      //   });
    },
    // 改，2022.10.29，新增
    // embedded_script() {
    //   let recaptchaScript = document.createElement("script");
    //   recaptchaScript.setAttribute("src", "https://widget.intercom.io/widget/hgs7jbgw");
    //   document.head.appendChild(recaptchaScript);
    // },
  },
};
</script>
<style>
/* 改，2022.12.30 使用主题色方案 */
@import "../../assets/css/theme.css";
@import "../../assets/css/common.css";
.m-mask {
  position: fixed;
  width: 100%;
  height: 100%;
  top: 0;
  left: 0;
  z-index: 9999;
}
</style>
