<template>
  <div class="m-page u-body u-xl-mode">
    <section class="u-black u-clearfix u-section-1" id="sec-75cc">
      <div class="u-clearfix u-sheet u-sheet-1">
        <h2 class="u-align-center u-text u-text-default u-text-1">Security</h2>
      </div>
    </section>
    <section class="u-black u-clearfix u-section-2" id="sec-472f">
      <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
        <div class="u-container-style u-grey-90 u-group u-group-1">
          <div class="u-container-layout u-valign-middle u-container-layout-1">
            <p class="u-align-center u-text u-text-default u-text-1">
              <span class="u-text-palette-1-base"> &nbsp; <b>Account Security Measures</b>
              </span>
              <br>
              <span style="font-size: 1rem; font-style: italic;">As an exchange, we prioritize the security of our users'
accounts and take several measures to ensure their protection.&nbsp;</span>
              <br>
              <span style="font-size: 1rem;">Here are some
key security measures we implement:</span>
              <span style="font-style: italic;"></span>
            </p>
          </div>
        </div>
      </div>
    </section>
    <section class="u-align-left u-black u-clearfix u-section-3" id="sec-a681">
      <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
        <div class="fr-view u-clearfix u-rich-text u-text u-text-1">
          <p id="isPasted">
            <span class="u-text-palette-1-base" style="font-weight: 700;">&nbsp;</span>
            <span style="font-weight: 700;font-size: 18px;">Two-Factor Authentication (2FA):</span><br>
            We strongly encourage our users to enable 2FA for their accounts. 2FA adds an extra layer of security by requiring users to provide a second form of authentication, such as a unique code generated by an authentication app or received via SMS, in addition to their regular login credentials.
          </p>
          <p>
            <span style="font-weight: 700;font-size: 18px;">Account Recovery Process:</span><br>
            In the event of a lost or compromised account, we have a robust account recovery process in place. This process typically involves verifying the user's identity through multiple factors, such as email verification, phone number verification, security questions, or other pre-defined recovery methods. This ensures that only authorized users can regain access to their accounts.
          </p>
          <p>
            <span style="font-weight: 700;font-size: 18px;">Strong Password Policies:</span><br>
            We enforce strong password policies to ensure that users create secure passwords. This includes requirements for minimum password length, a combination of uppercase and lowercase letters, numbers, and special characters. We also encourage users to regularly update their passwords and avoid using the same password across multiple platforms.
          </p>
          <p>
            <span style="font-weight: 700;font-size: 18px;">Account Activity Monitoring:</span><br>
            We employ sophisticated monitoring systems to detect and flag any suspicious or unauthorized account activity. Unusual login attempts, IP address changes, or other abnormal behaviors trigger security alerts, allowing us to promptly investigate and take appropriate action to protect our users' accounts.
          </p>
          <p>
            <span style="font-weight: 700;font-size: 18px;">Secure Socket Layer (SSL) Encryption:</span><br>
            We utilize SSL encryption to secure data transmission between our platform and users' devices. SSL encryption helps protect sensitive information, such as login credentials and personal details, from unauthorized access and interception.
          </p>
        </div>
      </div>
    </section>
    <section class="u-black u-clearfix u-section-4" id="carousel_f4b8">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-container-style u-grey-90 u-group u-group-1">
          <div class="u-container-layout u-container-layout-1">
            <p class="u-align-center u-text u-text-1">
              <span class="u-text-palette-1-base"> &nbsp; <b><b>Security Best Practices</b>&nbsp;&nbsp;</b>
              </span>
              <br>
              <span style="font-size: 1rem; font-style: italic;"> To enhance the overall security of user accounts, we recommend
following these best practices:&nbsp; &nbsp;&nbsp;</span>
              <br>
              <br>
            </p>
          </div>
        </div>
      </div>
    </section>
    <section class="u-align-left u-black u-clearfix u-section-5" id="carousel_e032">
      <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
        <div class="fr-view u-clearfix u-rich-text u-text u-text-1">
          <p id="isPasted">
            <span class="u-text-palette-1-base" style="font-weight: 700;">&nbsp;</span>
          </p>
          <p>
            <span style="font-weight: 700;">Regularly Update Software:</span> Keep your operating system, web browser, and security software up to date with the latest patches and updates. This helps protect against known vulnerabilities and security threats.
          </p>
          <p>
            <span style="font-weight: 700;">Be Cautious of Phishing Attempts:&nbsp;</span>Be vigilant and avoid clicking on suspicious links or providing personal information on unverified websites or in response to unsolicited emails. Phishing attacks often attempt to deceive users into revealing sensitive information.
          </p>
          <p>
            <span style="font-weight: 700;">Use Secure Internet Connections:</span> When accessing your account, use secure and trusted internet connections, especially when using public Wi-Fi networks. Public networks may be susceptible to eavesdropping and data interception.
          </p>
          <p>
            <span style="font-weight: 700;">Enable Account Notifications:&nbsp;</span>Activate account notifications and alerts to stay informed about any account-related activities, such as login attempts, withdrawals, or changes to security settings. This allows you to quickly identify and report any unauthorized access.
          </p>
          <p>
            <span style="font-weight: 700;">Regularly Monitor Account Activity:&nbsp;</span>Periodically review your account activity, transaction history, and login records. Report any suspicious or unrecognized activity to our customer support immediately.
          </p>
          <p>
            <span style="font-weight: 700;">Educate Yourself:</span> Stay informed about the latest security practices, potential risks, and emerging threats in the cryptocurrency ecosystem. This knowledge will help you make informed decisions and maintain the security of your account.
          </p>
          <p>By implementing these security measures and following best practices, we strive to provide a secure trading environment for our users, safeguarding their accounts and funds from potential threats.</p>
        </div>
      </div>
    </section>
    <section class="u-black u-clearfix u-section-6" id="carousel_e2d2">
      <div class="u-clearfix u-sheet u-valign-bottom u-sheet-1">
        <div class="u-container-style u-grey-90 u-group u-group-1">
          <div class="u-container-layout u-container-layout-1">
            <p class="u-align-center u-text u-text-1">
              <span class="u-text-palette-1-base"><b><b>Platform Security</b></b>
              </span>
              <br>
              <span style="font-size: 1rem; font-style: italic;"></span>
              <span style="font-size: 1rem;">
                <span style="font-style: italic;">Ensuring the security of our platform is a top priority for us.
We implement robust security measures to protect user data and prevent
unauthorized access.&nbsp;</span>
                <br>Our platform security includes:&nbsp;&nbsp;
              </span>
              <br>
              <br>
            </p>
          </div>
        </div>
      </div>
    </section>
    <section class="u-align-left u-black u-clearfix u-section-7" id="carousel_c3db">
      <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
        <div class="fr-view u-clearfix u-rich-text u-text u-text-1">
          <p id="isPasted">
            <span class="u-text-palette-1-base" style="font-weight: 700;">&nbsp;</span>
          </p>
          <p>
            <span style="font-weight: 700;">Firewalls and Intrusion Detection Systems:</span> We have firewalls and intrusion detection systems in place to monitor and block unauthorized access attempts and protect against malicious activities.
          </p>
          <p>
            <span style="font-weight: 700;">Secure Development Practices:</span> We follow secure coding practices during the development of our platform, adhering to industry standards and best practices to minimize vulnerabilities and potential security risks.
          </p>
          <p>
            <span style="font-weight: 700;">Incident Response Plan:</span> We have an incident response plan in place to swiftly and effectively respond to any security incidents or breaches. This includes measures to contain and mitigate the impact of such incidents, as well as communication protocols to keep users informed.
          </p>
        </div>
      </div>
    </section>
    <section class="u-black u-clearfix u-section-8" id="carousel_2cf2">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-container-style u-grey-90 u-group u-group-1">
          <div class="u-container-layout u-container-layout-1">
            <p class="u-align-center u-text u-text-1">
              <span class="u-text-palette-1-base"><b>Encryption and Data Protection</b>
              </span>
              <br>
              <span style="font-style: italic; font-size: 1rem;">We prioritize the encryption and protection of user data to
maintain confidentiality and integrity. Our encryption and data protection
practices include:&nbsp;&nbsp;</span>
              <br>
              <br>
            </p>
          </div>
        </div>
      </div>
    </section>
    <section class="u-align-left u-black u-clearfix u-section-9" id="carousel_646d">
      <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
        <div class="fr-view u-clearfix u-rich-text u-text u-text-1">
          <p id="isPasted">
            <span class="u-text-palette-1-base" style="font-weight: 700;">&nbsp;</span>
            <span style="font-weight: 700;">Transport Layer Security (TLS): </span>We use TLS encryption to secure the communication between our platform and users' devices. This safeguards sensitive information, such as login credentials and financial data, during transmission.
          </p>
          <p>
            <span style="font-weight: 700;">Secure Storage:</span> User data, including personal information and transaction details, is securely stored using industry-standard encryption algorithms. This helps protect the data from unauthorized access even in the event of a breach.
          </p>
          <p>
            <span style="font-weight: 700;">Privacy Policies:</span> We have strict privacy policies in place to govern the collection, storage, and use of user data. We ensure compliance with applicable data protection regulations and prioritize user consent and transparency.
          </p>
        </div>
      </div>
    </section>
    <section class="u-align-left u-black u-clearfix u-section-10" id="carousel_803e">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="fr-view u-clearfix u-rich-text u-text u-text-1">
          <p id="isPasted">
            <span class="u-text-palette-1-base" style="font-weight: 700;">&nbsp;</span>
          </p>
          <p id="isPasted">
            <span class="u-text-palette-1-base" style="font-weight: 700;">Cold Storage Solutions</span>
          </p>
          <p>To enhance the security of user funds, we utilize cold storage solutions. Cold storage refers to storing cryptocurrencies in offline wallets or devices that are not connected to the internet. This approach minimizes the risk of online attacks or unauthorized access. The majority of user funds are stored in cold wallets, ensuring an additional layer of protection against potential security breaches.</p>
          <p>
            <br>
            <span class="u-text-palette-1-base" style="font-weight: 700;">Regular Security Audits</span>
          </p>
          <p>We conduct regular security audits and assessments to evaluate the effectiveness of our security measures and identify any potential vulnerabilities. By conducting periodic security audits, we can identify and address any security weaknesses promptly, ensuring the ongoing protection of our platform and user data.</p>
          <p>Our commitment to platform security, encryption, cold storage solutions, and regular security audits reflects our dedication to maintaining a secure environment for our users' accounts, personal information, and funds.</p>
          <p>We strive to stay up to date with evolving security practices and technologies to provide the highest level of protection possible.</p>
        </div>
      </div>
    </section>
  </div>
</template>

<script>
export default {
  name: "security",
};
</script>

<style scoped>
.u-section-1 {
  background-image: none;
}

.u-section-1 .u-sheet-1 {
  min-height: 204px;
}

.u-section-1 .u-text-1 {
  font-weight: 700;
  margin: 101px auto 60px;
}.u-section-2 .u-sheet-1 {
   min-height: 218px;
 }

.u-section-2 .u-group-1 {
  width: 976px;
  min-height: 218px;
  height: auto;
  margin: 0 auto;
}

.u-section-2 .u-container-layout-1 {
  padding: 30px;
}

.u-section-2 .u-text-1 {
  font-size: 1.125rem;
  line-height: 2;
  margin: 0;
}

@media (max-width: 1199px) {
  .u-section-2 .u-group-1 {
    height: auto;
  }
}

@media (max-width: 991px) {
  .u-section-2 .u-group-1 {
    width: 720px;
  }
}

@media (max-width: 767px) {
  .u-section-2 .u-group-1 {
    width: 540px;
  }
}

@media (max-width: 575px) {
  .u-section-2 .u-group-1 {
    width: 340px;
  }
} .u-section-3 {
    background-image: none;
  }

.u-section-3 .u-sheet-1 {
  min-height: 506px;
}

.u-section-3 .u-text-1 {
  margin: 1px 0;
}

@media (max-width: 767px) {
  .u-section-3 .u-text-1 {
    margin-bottom: 60px;
  }
}.u-section-4 .u-sheet-1 {
   min-height: 291px;
 }

.u-section-4 .u-group-1 {
  width: 976px;
  min-height: 218px;
  height: auto;
  margin: 73px auto 0;
}

.u-section-4 .u-container-layout-1 {
  padding: 30px;
}

.u-section-4 .u-text-1 {
  font-size: 1.125rem;
  line-height: 2;
  margin: 25px 0 0;
}

@media (max-width: 1199px) {
  .u-section-4 .u-group-1 {
    height: auto;
  }
}

@media (max-width: 991px) {
  .u-section-4 .u-group-1 {
    width: 720px;
  }
}

@media (max-width: 767px) {
  .u-section-4 .u-group-1 {
    width: 540px;
  }
}

@media (max-width: 575px) {
  .u-section-4 .u-group-1 {
    width: 340px;
  }
} .u-section-5 {
    background-image: none;
  }

.u-section-5 .u-sheet-1 {
  min-height: 506px;
}

.u-section-5 .u-text-1 {
  margin: 1px 0;
}

@media (max-width: 767px) {
  .u-section-5 .u-text-1 {
    margin-bottom: 60px;
  }
}.u-section-6 .u-sheet-1 {
   min-height: 302px;
 }

.u-section-6 .u-group-1 {
  width: 976px;
  min-height: 265px;
  height: auto;
  margin: 74px auto 0;
}

.u-section-6 .u-container-layout-1 {
  padding: 30px;
}

.u-section-6 .u-text-1 {
  font-size: 1.125rem;
  line-height: 2;
  margin: 25px 0 0;
}

@media (max-width: 1199px) {
  .u-section-6 .u-group-1 {
    height: auto;
  }
}

@media (max-width: 991px) {
  .u-section-6 .u-group-1 {
    width: 720px;
  }
}

@media (max-width: 767px) {
  .u-section-6 .u-group-1 {
    width: 540px;
  }
}

@media (max-width: 575px) {
  .u-section-6 .u-group-1 {
    width: 340px;
  }
} .u-section-7 {
    background-image: none;
  }

.u-section-7 .u-sheet-1 {
  min-height: 260px;
}

.u-section-7 .u-text-1 {
  margin: 1px 0;
}.u-section-8 .u-sheet-1 {
   min-height: 339px;
 }

.u-section-8 .u-group-1 {
  width: 976px;
  min-height: 265px;
  height: auto;
  margin: 58px auto 16px;
}

.u-section-8 .u-container-layout-1 {
  padding: 30px;
}

.u-section-8 .u-text-1 {
  font-size: 1.125rem;
  line-height: 2;
  margin: 25px 0 0;
}

@media (max-width: 1199px) {
  .u-section-8 .u-group-1 {
    height: auto;
  }
}

@media (max-width: 991px) {
  .u-section-8 .u-group-1 {
    width: 720px;
  }
}

@media (max-width: 767px) {
  .u-section-8 .u-group-1 {
    width: 540px;
  }
}

@media (max-width: 575px) {
  .u-section-8 .u-group-1 {
    width: 340px;
  }
} .u-section-9 {
    background-image: none;
  }

.u-section-9 .u-sheet-1 {
  min-height: 216px;
}

.u-section-9 .u-text-1 {
  margin: 1px 0;
}

@media (max-width: 767px) {
  .u-section-9 .u-text-1 {
    margin-bottom: 60px;
  }
} .u-section-10 {
    background-image: none;
  }

.u-section-10 .u-sheet-1 {
  min-height: 559px;
}

.u-section-10 .u-text-1 {
  margin: 1px 0 60px;
}
</style>
